name: nginx_le_cli
version: 0.2.0
homepage: https://github.com/bsutton/nginx-le
description: Command line tools for Nginx-LE
environment: 
  sdk: '>=2.8.0 <3.0.0'
dependencies: 
  async: ^2.4.2
  args: ^1.5.2
  encrypt: ^4.0.2
  path: ^1.6.4
  cron: ^0.2.3
  dshell: ^1.9.12
  xml: ^4.2.0
  http: ^0.12.1
  intl: ^0.16.1
  isolate: ^2.0.3
  meta: ^1.0.0
  pedantic: ^1.0.0
  public_suffix: ^1.0.0
  uuid: ^2.0.4
  yaml: ^2.2.0
  nginx_le_shared: ^0.2.0
    #path: ../shared
dev_dependencies: 
  test: ^1.0.0
executables: 
  nginx-le: nginx-le
