name: nginx_le_shared
version: 0.5.3
homepage: https://github.com/bsutton/nginx-le
description: shared library used by Nginx-LE
environment: 
  sdk: '>=2.8.0 <3.0.0'
dependencies: 
  async: ^2.4.2
  args: ^1.5.2
  path: ^1.6.4
  cron: ^0.2.3
  dshell: ^1.9.12
  instant: ^0.3.2
  http: ^0.12.1
  intl: ^0.16.1
  isolate: ^2.0.3
  meta: ^1.0.0
  pedantic: ^1.0.0
  public_suffix: ^1.0.0
  uuid: ^2.0.4
  xml: ^4.2.0
  yaml: ^2.2.1
dev_dependencies: 
  test: ^1.0.0
